branch-defaults:
  master:
    environment: hunqry
    group_suffix: null
environment-defaults:
  hunqry:
    branch: null
    repository: null
global:
  application_name: hunqry_backend
  branch: null
  default_ec2_keyname: hunqry12
  default_platform: Node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
